### ISSUE TITLE
Plugin Transfer: <plugin name>

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker/governance#186] opened 2020-10-07 19:45 UTC
### Plugin Information

Account Registration Plugin

The accounts registration plugin implements the [Spinnaker Account Management RFC](https://github.com/spinnaker/governance/blob/master/rfc/account-management.md) to allow Spinnaker accounts to be added dynamically from an external source (wired over HTTP) without having to restart Clouddriver. The plugin serves as a first implementation of the RFC and can be used both to load external accounts into Clouddriver and also as an example for others interested in interfacing with the Clouddriver and supplying account data dynamically. While the implementation can technically be modified to accommodate any type of account, the current implementation only supports EC2, ECS, and Lambda accounts.

The current plugin lives here: [awslabs/aws-account-registration-plugin-spinnaker](https://github.com/awslabs/aws-account-registration-plugin-spinnaker)

### Acknowledgements

- [ ] Source code will be available publicly on [`spinnaker-plugins`](https://github.com/spinnaker-plugins)
- [ ] Donated code must explicitly declare a license
- [ ] All authors listed below will be given `maintain` permissions to the plugin repository
- [ ] Plugin authors are expected to continue as primary maintainers of plugin
- [ ] Spinnaker core contributors are not expected to help maintain the plugin
- [ ] Spinnaker core contributors will not automatically inherit permissions for plugin repository, with the exception of the Technical Oversight Committee for administrative purposes

### Maintainers

@dkirillov @ncknt @nimakaviani

**Comment by robzienert** [comment] 2020-10-08 19:01
Looks like a duplicate of #187 - closing.

**Closed by robzienert** 2020-10-08 19:01 UTC
Labels: committee/technical-oversight
